Repository qfall/crypto, pull requests merged in 2023-09, with the labels that each got.

#42 Update README.md
  README.md
Labels: documentation📖

#35 Identity based encryption
  src/construction.rs
  src/construction/identity_based_encryption.rs
  src/construction/identity_based_encryption/dual_regev_ibe.rs
  src/construction/pk_encryption.rs
  src/construction/pk_encryption/dual_regev.rs
  src/primitive/hash.rs
  src/sample/g_trapdoor/gadget_parameters.rs
Labels: enhancement📈

#38 Refactor
  src/construction/hash.rs
  src/construction/hash/sha256.rs
  src/construction/hash/sis.rs
  src/construction/identity_based_encryption/dual_regev_ibe.rs
  src/construction/pk_encryption/dual_regev.rs
  src/construction/pk_encryption/dual_regev_discrete_gauss.rs
  src/construction/pk_encryption/lpr.rs
  src/construction/pk_encryption/regev.rs
  src/construction/pk_encryption/regev_discrete_gauss.rs
  src/construction/pk_encryption/ring_lpr.rs
  src/construction/signature/fdh.rs
  src/construction/signature/fdh/gpv.rs
  src/construction/signature/fdh/gpv_ring.rs
  src/construction/signature/fdh/serialize.rs
  src/construction/signature/pfdh.rs
  src/construction/signature/pfdh/gpv.rs
  src/construction/signature/pfdh/serialize.rs
  src/primitive.rs
  src/primitive/psf.rs
  src/primitive/psf/gpv.rs
  src/primitive/psf/gpv_ring.rs
  src/sample.rs
  src/sample/distribution.rs
  src/sample/distribution/binomial.rs
  src/sample/distribution/discrete_gauss.rs
  src/sample/distribution/psf.rs
  src/sample/distribution/uniform.rs
  src/sample/g_trapdoor.rs
  src/sample/g_trapdoor/gadget_classical.rs
  src/sample/g_trapdoor/gadget_parameters.rs
  src/sample/g_trapdoor/gadget_ring.rs
  src/sample/g_trapdoor/short_basis_classical.rs
  src/sample/g_trapdoor/short_basis_ring.rs
  src/sample/g_trapdoor/trapdoor_distribution.rs
  src/sample/lattice_problem.rs
  src/sample/lattice_problem/lwe.rs
  src/sample/lattice_problem/sis.rs
  src/utils/rotation_matrix.rs
Labels: refactoring :tractor:

#43 Common Moduli
  src/construction/pk_encryption/ring_lpr.rs
  src/sample/g_trapdoor/gadget_parameters.rs
  src/utils.rs
  src/utils/common_moduli.rs
Labels: enhancement📈

#44 IND-CCS from IBE
  benches/pfdh.rs
  src/construction/identity_based_encryption.rs
  src/construction/identity_based_encryption/dual_regev_ibe.rs
  src/construction/pk_encryption.rs
  src/construction/pk_encryption/ccs_from_ibe.rs
  src/construction/pk_encryption/ccs_from_ibe/dual_regev_ibe_pfdh.rs
  src/construction/signature/fdh.rs
  src/construction/signature/fdh/gpv.rs
  src/construction/signature/fdh/gpv_ring.rs
  src/construction/signature/fdh/serialize.rs
  src/construction/signature/pfdh.rs
  src/construction/signature/pfdh/gpv.rs
  src/construction/signature/pfdh/serialize.rs
Labels: enhancement📈

#46 Add Meaningful Module and Crate Descriptions
  benches/pfdh.rs
  src/construction.rs
  src/construction/identity_based_encryption.rs
  src/construction/identity_based_encryption/dual_regev_ibe.rs
  src/construction/pk_encryption/ccs_from_ibe/dual_regev_ibe_pfdh.rs
  src/construction/signature.rs
  src/construction/signature/fdh.rs
  src/construction/signature/fdh/gpv.rs
  src/construction/signature/fdh/gpv_ring.rs
  src/construction/signature/fdh/serialize.rs
  src/construction/signature/pfdh.rs
  src/construction/signature/pfdh/gpv.rs
  src/construction/signature/pfdh/serialize.rs
  src/lib.rs
  src/primitive/psf.rs
  src/primitive/psf/gpv.rs
  src/primitive/psf/gpv_ring.rs
  src/sample/g_trapdoor.rs
Labels: documentation📖, refactoring :tractor:

#47 Refactoring
  benches/regev.rs
  src/construction.rs
  src/construction/hash.rs
  src/construction/hash/sha256.rs
  src/construction/identity_based_encryption.rs
  src/construction/identity_based_encryption/dual_regev_ibe.rs
  src/construction/pk_encryption.rs
  src/construction/pk_encryption/ccs_from_ibe.rs
  src/construction/pk_encryption/ccs_from_ibe/dual_regev_ibe_pfdh.rs
  src/construction/pk_encryption/dual_regev.rs
  src/construction/pk_encryption/dual_regev_discrete_gauss.rs
  src/construction/pk_encryption/lpr.rs
  src/construction/pk_encryption/regev.rs
  src/construction/pk_encryption/regev_discrete_gauss.rs
  src/construction/pk_encryption/ring_lpr.rs
  src/construction/signature.rs
  src/construction/signature/fdh/gpv.rs
  src/construction/signature/fdh/gpv_ring.rs
  src/construction/signature/pfdh/gpv.rs
  src/lib.rs
  src/primitive/psf.rs
  src/primitive/psf/gpv.rs
  src/primitive/psf/gpv_ring.rs
  src/sample/g_trapdoor.rs
  src/sample/g_trapdoor/gadget_parameters.rs
  src/sample/g_trapdoor/trapdoor_distribution.rs
Labels: refactoring :tractor:

#48 fixed comments for PSFs
  src/primitive/psf.rs
  src/primitive/psf/gpv_ring.rs
Labels: refactoring :tractor:

#50 Update readme
  README.md
Labels: refactoring :tractor:

#49 Fixed documentation
  src/construction/hash.rs
  src/construction/identity_based_encryption.rs
  src/construction/signature.rs
  src/primitive.rs
  src/sample/g_trapdoor.rs
  src/sample/g_trapdoor/gadget_classical.rs
Labels: refactoring :tractor:
